### ISSUE TITLE
[Bug] react-native-svg 버전 관련 버그

### ISSUE THREAD

**Issue by JAM-PARK** [infinite-loop-factory/app-factory#50]
## 요약 (Summary)

- gluestack이 설치해주는 `react-native-svg 13.4.0`은 안드로이드에서 에러 발생
- `14.1.0`버전으로 업데이트하면 안드로이드 문제 없음
- `pnpm-workspace.yaml` 카탈로그에 `react-native-svg: 14.1.0` 추가할까요?

---

~으아아악 도르마무~

### 신규 이슈 related #47

- `react-native-css-interop: ^0.1.20` 기준으론 ios/android 둘 다 번들링 에러가 발생합니다
```
iOS Bundling failed 29216ms index.ts (1669 modules)
Unable to resolve "react-native-css-interop/dist/metro/poll-update-client" from "global.css"
› Stopped server
```
![Image](https://github.com/user-attachments/assets/dc457d28-e68d-4b46-8d95-fb65e3465ca3)

### 정리

`react-native-svg 13.4.0`은 `react-native-css-interop`버전 상관없이 앱에서 에러 발생 👉 `react-native-svg: 14.1.0` 사용
`react-native-svg: 14.1.0` + `react-native-css-interop: ^0.0.36 (canary)`버전만 정상 작동 확인
`react-native-svg: 14.1.0` + `react-native-css-interop: ^0.1.22 (latest)` 👉 에러
`react-native-svg: 14.1.0` + `react-native-css-interop: ^0.1.18 (next)` 👉 에러

## 스크린샷/동영상 (Screenshots/Videos)

- `react-native-svg 13.4.0`
![Image](https://github.com/user-attachments/assets/e25352aa-0aa3-4e90-a054-a67e52c7742d)
- `react-native-svg 14.1.0` + `react-native-css-interop: ^0.0.36`
![Image](https://github.com/user-attachments/assets/b526a375-d8e8-4a2f-bc6a-d748ce167d69)

## 체크리스트 (Checklist)

> 아래 플랫폼에서 모두 확인하셨나요?

- [x] iOS
- [x] Android
- [x] 웹

## 추가 정보 (Additional Context)

- [react-native-svg 버전 문제라고 확인한 깃헙 이슈](https://github.com/software-mansion/react-native-svg/issues/1944)
- [동일 에러 로그가 있지만 댓글 답변으로 해결하지 못한 이슈](https://github.com/nativewind/nativewind/issues/894#issuecomment-2323526962)
네이티브윈드 레포 이슈입니다... **네이티브윈드 버전**도 맞춰야 하는 걸까요🥲
- [npm react-native-css-interop versions](https://www.npmjs.com/package/react-native-css-interop?activeTab=versions)

우선 정상 작동하는 `react-native-svg 14.1.0` + `react-native-css-interop: ^0.0.36`로 작업하려고 합니다😩

## 241117 내용 업데이트
>metro.config.js 에 patchNativeWind 없이 빌드할 때도 동일하다면 지금 그 버전조합으로 사용해야할 것 같네요,
아니면 nativewind 2주전 나온 버전이랑 react-native-css-interop 최신 버전으로 테스트해봐야할 것 같습니다~

`metro.config.js` 수정 없이(=`patchNativeWind` 적용) `nativewind@latest`와 `react-native-css-interop@latest`로
정상 작동 확인했습니다

### 관련 커밋
- 3321f4e
- 8eec855

### svg 작동을 위해 업데이트한 라이브러리 목록
- "nativewind": "4.0.36" 👉 "4.1.23"
- "react-native-css-interop": "0.0.36" 👉 "^0.1.22"
- "react-native-svg": "13.4.0" 👉 "14.1.0"

### 241123 #52 merge 이후 closed 예정

**Comment by gracefullight** [comment]
metro.config.js 에 patchNativeWind 없이 빌드할 때도 동일하다면 지금 그 버전조합으로 사용해야할 것 같네요,
아니면 nativewind 2주전 나온 버전이랑 react-native-css-interop 최신 버전으로 테스트해봐야할 것 같습니다~

PR 올라오면 저도 실행해볼게요.

**Comment by JAM-PARK** [comment]
@gracefullight `본 이슈 상황 === 최신 커밋`인 PR 내일 오전까지 올리겠습니다...! 
저도 내일
> nativewind 2주전 나온 버전이랑 react-native-css-interop 최신 버전으로 테스트

해보겠습니다~

**Comment by JAM-PARK** [comment]
@gracefullight 
>nativewind 2주전 나온 버전이랑 react-native-css-interop 최신 버전으로 테스트

로 잘 작동합니다! 이슈 본문 하단에 내용 업데이트 했습니다.
버전 업데이트한 라이브러리들 pnpm catalog 작업 필요할까요?

감사합니다🙇‍♂️

**Comment by gracefullight** [comment]
> [@gracefullight](https://github.com/gracefullight)
> 
> > nativewind 2주전 나온 버전이랑 react-native-css-interop 최신 버전으로 테스트
> 
> 로 잘 작동합니다! 이슈 본문 하단에 내용 업데이트 했습니다. 버전 업데이트한 라이브러리들 pnpm catalog 작업 필요할까요?
> 
> 감사합니다🙇‍♂️

네 적용 부탁드려요~
