### ISSUE TITLE
[Bug] tailwindcss 미적용 이슈

### ISSUE THREAD

**Issue by JAM-PARK** [infinite-loop-factory/app-factory#60]
## 요약 (Summary)

[@gaa0 님 #58 기준으로 만든 브랜치](https://github.com/infinite-loop-factory/app-factory/commits/feature/playlist-jampark/)에 커밋 추가했습니다
참고해서 작업해주세요~  `feature/playlist-jampark` 브랜치는 나중에 레포에서 지울게요
- tailwind가 적용 안된 가장 큰 이유는 ad28186 입니다
  - global.css에 있는 3줄이 tailwind 적용에 핵심인데요, RootLayout에서 import 해줘야 app 전체에 적용이 됩니다
- 7cd5c31 요건 단순 경고 해결이구요
  - RootLayout에 이미 있어서 커밋 위치에서는 제거해도 괜찮을 것 같아요
  ```tsx
  <Stack.Screen name="+not-found" />
  ```
- metro.config.js도 최신화 해놨습니다
  - patchNativeWind 함수: 빌드시 플랫폼 별 CSS 관리

## 스크린샷/동영상 (Screenshots/Videos)
![Image](https://github.com/user-attachments/assets/de587516-0fb8-45f8-8743-bf19daf01b6b)

## 체크리스트 (Checklist)

> 아래 플랫폼에서 모두 확인하셨나요?

- [x] iOS
- [ ] Android
- [x] 웹

## 추가 정보 (Additional Context)

- 아직 남은 ~찜찜한~ warning
  - web에서 뜨네요
    - λ  WARN  props.pointerEvents is deprecated. Use style.pointerEvents
    - "shadow*" style props are deprecated. Use "boxShadow".
  - 구글링하면 expo 버전, web 호환 이슈로 보이는데요, 코드 어디가 문제인지 모르겠습니다😅

**Comment by gracefullight** [comment]
예상외로 스타일 임포트가 없어서 발생한 간단한 이슈였군요.. 감사합니다. @gaa0 적용 부탁드려요~~

**Comment by gaa0** [comment]
원인 찾아주시고 친절한 설명까지 고맙습니다 재민님! 🙌🏻

**Comment by gracefullight** [comment]
클로즈 고고
